- id: "1679781150922"
  alias: Low battery level detection & notification
  description: ""
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      threshold: 20
      exclude:
        entity_id:
          - sensor.iphone_12_az_battery_level
          - sensor.ipad_6_battery_level
          - sensor.h5075_66f8_battery
      actions:
        - service: notify.tg_valaz # notify.mobile_app_iphone_12_az
          data:
            message: "Замени батареи: {{sensors}}"
            title: Низкий уровень заряда
