- id: "1679781150922"
  alias: Low battery level detection & notification
  description: ""
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      threshold: 20
      exclude:
        entity_id:
          - sensor.ipad_6_battery_level
          - sensor.iphone_15_az_battery_level
          - sensor.ipad_m1_battery_level
      actions:
        - service: notify.tg_valaz
          data:
            message: "Замени батареи: {{sensors}}"
            title: Низкий уровень заряда
