homeassistant:
  name: Tegel Home
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml
  packages: !include_dir_merge_named includes/packages
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.18.0.100
    - 172.30.33.8
    - 192.168.178.6
    - 10.13.13.1

homekit: !include includes/homekit.yaml

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: js
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/home-assistant-sun-card/home-assistant-sun-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/battery-state-card/battery-state-card.js
      type: module
    - url: /hacsfiles/logbook-card/logbook-card.js
      type: module
    - url: /hacsfiles/entity-attributes-card/entity-attributes-card.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-tempometer-gauge-card-deprecated/tempometer-gauge-card.js
      type: module
    - url: /hacsfiles/flipdown-timer-card/flipdown-timer-card.js
      type: module
    - url: /hacsfiles/vacuum-card/vacuum-card.js
      type: module
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: module
    - url: /hacsfiles/lovelace-plotly-graph-card/plotly-graph-card.js
      type: module
    - url: /hacsfiles/history-explorer-card/history-explorer-card.js
      type: module
    - url: /hacsfiles/lovelace-swipe-navigation/swipe-navigation.js
      type: module
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/my-cards/my-cards.js
      type: module
    - url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-state-switch/state-switch.js
      type: module
    - url: /hacsfiles/apexcharts-card/apexcharts-card.js
      type: module
    - url: /hacsfiles/hass-shutter-card/hass-shutter-card.js
      type: module
    - url: /hacsfiles/weather-radar-card/weather-radar-card.js
      type: module

# Вынос во внешние файлы
timer: !include includes/timer.yaml
group: !include includes/groups.yaml
scene: !include includes/scenes.yaml
recorder: !include includes/recorder.yaml
vacuum: !include includes/vacuum.yaml
fan: !include includes/fan.yaml
remote: !include includes/remote.yaml
media_player: !include includes/media_player.yaml
camera: !include includes/camera.yaml

# Вынос во внешние папки
sensor: !include_dir_merge_list includes/sensors
automation: !include automations.yaml
automation manual: !include_dir_merge_list includes/automations
switch: !include_dir_merge_list includes/switches
script: !include scripts.yaml
script manual: !include_dir_merge_named includes/scripts
shell_command: !include_dir_merge_named includes/shell_commands
binary_sensor: !include_dir_merge_list includes/bin_sensors
input_select: !include_dir_merge_named includes/input_selects
input_number: !include_dir_merge_named includes/input_numbers
input_boolean: !include_dir_merge_named includes/input_booleans
input_datetime: !include_dir_merge_named includes/input_datetimes
alert: !include_dir_merge_named includes/alerts
rest_command: !include_dir_merge_named includes/rest_commands
zone: !include_dir_merge_list includes/zones

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

influxdb:
  api_version: 2
  ssl: false
  host: localhost
  port: 8086
  token: !secret influxdb_token
  organization: !secret influxdb_org
  bucket: !secret influxdb_bucket
  default_measurement: state
  component_config_glob:
    sensor.*humidity:
      override_measurement: humidity
    sensor.*temperature:
      override_measurement: temperature
    sensor.*battery*:
      override_measurement: battery
    sensor.*power*:
      override_measurement: energy
    sensor.*energy*:
      override_measurement: energy
    sensor.pi_hole*:
      override_measurement: pi_hole
  tags:
    source: HA
  tags_attributes:
    - room
    - device_class
    - friendly_name

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret tg_valaz_id

notify:
  - name: tg_valaz
    platform: telegram
    chat_id: !secret tg_valaz_id
