title: Home Assistant Tegel
views:
  - !include lovelace/01_home.yaml
  - !include lovelace/02_climate.yaml
  - !include lovelace/03_devices.yaml
  - !include lovelace/02_homelab.yaml
  - !include lovelace/31_automation.yaml
