title: Home Assistant Tegel
views:
  - !include lovelace/home/home.yaml
  - !include lovelace/home/rooms/bedroom.yaml
  - !include lovelace/home/rooms/hallway.yaml
  - !include lovelace/home/rooms/livingroom.yaml
  - !include lovelace/home/climate.yaml
  - !include lovelace/home/vacuum.yaml
  - !include lovelace/home/devices.yaml

