- alias: "[Bedroom] Restart Bluetooth if clock disconnected"
  trigger:
    - platform: state
      entity_id: sensor.temperature_humidity_sensor_0c8f_temperature
      to: "unavailable"
  action:
    - service: script.bluetooth_restart

- alias: "[Bedroom] Turn Off all lights on charge"
  trigger:
    - platform: numeric_state
      entity_id: sensor.0x04cf8cdf3c777c79_power
      above: 2
  action:
    - service: light.turn_off
      target:
        entity_id: light.hallway
    - service: light.turn_off
      target:
        entity_id: light.livingroom
