- alias: "[Bedroom] Turn Off all lights on charge"
  trigger:
    - platform: numeric_state
      entity_id: sensor.0x04cf8cdf3c777c79_power
      above: 2
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 0
  action:
    - service: light.turn_off
      target:
        entity_id: light.hallway
    - service: light.turn_off
      target:
        entity_id: light.livingroom
    - service: switch.turn_off
      target:
        entity_id: switch.0x54ef4410007df222_right
    - service: switch.turn_off
      target:
        entity_id: switch.0xa4c1386f1ce92e1c

- alias: "[Bedroom] Turn on Monitor on sunrise"
  trigger:
    - platform: sun
      event: sunrise
      offset: "00:30:00"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.0xa4c1386f1ce92e1c
