- alias: "[Bedroom] Turn Off all lights on charge"
  trigger:
    - platform: numeric_state
      entity_id: sensor.bedroom_charging_dock_plug_power
      above: 2
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 0
  action:
    - service: light.turn_off
      target:
        entity_id: light.hallway
    - service: light.turn_off
      target:
        entity_id: light.livingroom
    - service: switch.turn_off
      target:
        entity_id: switch.kitchen_light_switch_right
    - service: switch.turn_off
      target:
        entity_id: switch.bedroom_monitor_plug

- alias: "[Bedroom] Turn on Monitor on sunrise"
  trigger:
    - platform: sun
      event: sunrise
      offset: "00:30:00"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.bedroom_monitor_plug
