- alias: "[Pi-hole] Start timer when Pi-hole disabled"
  trigger:
  - platform: state
    entity_id: switch.pi_hole
    to: "off"
  action:
  - service: timer.cancel
    target:
        entity_id: timer.pihole
  - service: timer.start
    target:
        entity_id: timer.pihole
        
- alias: "[Pi-hole] Cancel timer when Pi-hole enabled"
  trigger:
  - platform: state
    entity_id: switch.pi_hole
    to: "on"
  action:
  - service: timer.cancel
    target:
        entity_id: timer.pihole
        
- alias: "[Pi-hole] Enable Pi-hole after timer finished"
  trigger:
  - platform: state
    entity_id: switch.pi_hole
    to: "off"
    for: "00:05:00"
  action:
    service: switch.turn_on
    target:
      entity_id:
        - switch.pi_hole
        