- platform: rest
  resource: http://192.168.178.4:8126/container/heimdall
  name: c_hulk_docker_heimdall
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  headers:
    Content-Type: application/octet-stream

- platform: rest
  resource: http://192.168.178.4:8126/container/pihole
  name: c_hulk_docker_pihole
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  headers:
    Content-Type: application/octet-stream

- platform: rest
  resource: http://192.168.178.4:8126/container/grafana
  name: c_hulk_docker_grafana
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  headers:
    Content-Type: application/octet-stream

- platform: rest
  resource: http://192.168.178.4:8126/container/influxdb-2
  name: c_hulk_docker_influxdb-2
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  headers:
    Content-Type: application/octet-stream

- platform: rest
  resource: http://192.168.178.4:8126/container/uptime-kuma
  name: c_hulk_docker_uptime-kuma
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  headers:
    Content-Type: application/octet-stream

- platform: rest
  resource: http://192.168.178.4:8126/container/nginx-proxy-manager
  name: c_hulk_docker_nginx-proxy-manager
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  headers:
    Content-Type: application/octet-stream

- platform: rest
  resource: http://192.168.178.4:8126/container/gluetun-asus
  name: c_hulk_docker_gluetun-asus
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  headers:
    Content-Type: application/octet-stream

- platform: rest
  resource: http://192.168.178.4:8126/container/nginx-proxy-manager-msk
  name: c_hulk_docker_nginx-proxy-manager-msk
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  headers:
    Content-Type: application/octet-stream

- platform: rest
  resource: http://192.168.178.4:8126/container/syncthing
  name: c_hulk_docker_syncthing
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  headers:
    Content-Type: application/octet-stream

- platform: rest
  resource: http://192.168.178.4:8126/container/arch-minidlna
  name: c_hulk_docker_arch-minidlna
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  headers:
    Content-Type: application/octet-stream

- platform: rest
  resource: http://192.168.178.4:8126/container/plex
  name: c_hulk_docker_plex
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  headers:
    Content-Type: application/octet-stream

- platform: rest
  resource: http://192.168.178.4:8126/container/filebrowser
  name: c_hulk_docker_filebrowser
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  headers:
    Content-Type: application/octet-stream

- platform: rest
  resource: http://192.168.178.4:8126/container/portainer
  name: c_hulk_docker_portainer
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  headers:
    Content-Type: application/octet-stream

- platform: rest
  resource: http://192.168.178.4:8126/container/scrypted
  name: c_hulk_docker_scrypted
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  headers:
    Content-Type: application/octet-stream

- platform: rest
  resource: http://192.168.178.4:8126/container/hassio_supervisor
  name: c_hulk_docker_hassio_supervisor
  body_on: '{"state": "restart"}'
  body_off: '{"state": "restart"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  headers:
    Content-Type: application/octet-stream
