- platform: template
  sensors:
    c_bathroom_moisture:
      friendly_name: "Bathroom Moisture"
      value_template: >-
        {{states.sensor.c_bathroom_humidity.state | float >= 60 and states.sensor.c_bathroom_humidity.state | float > states.sensor.c_weather_humidity.state | float}}

    c_bedroom_high_co2:
      friendly_name: "Bedroom High CO2 level"
      value_template: >-
        {{states('sensor.c_bedroom_co2_density') | float >= 700 }}
