- platform: template
  sensors:
    # BEDROOM CLIMATE
    c_bedroom_temperature:
      friendly_name: "Bedroom Temeperature"
      value_template: >
        {{ states('sensor.bedroom_air_sensor_temperature')  | round(2) }}
      unit_of_measurement: "°C"
      device_class: temperature
      icon_template: mdi:thermometer
      availability_template: "{{ is_number(states('sensor.bedroom_air_sensor_temperature')) }}"

    c_bedroom_humidity:
      friendly_name: "Bedroom Humidity"
      value_template: >
        {{ states('sensor.bedroom_air_sensor_humidity') }}
      unit_of_measurement: "%"
      device_class: humidity
      icon_template: mdi:water-percent
      availability_template: "{{ is_number(states('sensor.bedroom_air_sensor_humidity')) }}"

    c_bedroom_pressure:
      friendly_name: "Bedroom Pressure"
      value_template: >
        {{ states('sensor.bedroom_air_sensor_pressure') }}
      unit_of_measurement: hPa
      device_class: atmospheric_pressure
      icon_template: mdi:thermometer-lines
      availability_template: "{{ is_number(states('sensor.bedroom_air_sensor_pressure')) }}"

    c_bedroom_pm25_density:
      friendly_name: "Bedroom pm2.5 Density"
      value_template: >
        {{ states('sensor.cgllc_cgd1st_c37c_pm25_density') }}
      unit_of_measurement: "µg/m³"
      device_class: pm25
      icon_template: mdi:blur
      availability_template: "{{ is_number(states('sensor.cgllc_cgd1st_c37c_pm25_density')) }}"

    c_bedroom_pm10_density:
      friendly_name: "Bedroom pm10 Density"
      value_template: >
        {{ states('sensor.cgllc_cgd1st_c37c_pm10_density') }}
      unit_of_measurement: "µg/m³"
      device_class: pm10
      icon_template: mdi:blur
      availability_template: "{{ is_number(states('sensor.cgllc_cgd1st_c37c_pm10_density')) }}"

    c_bedroom_co2_density:
      friendly_name: "Bedroom CO2 Density"
      value_template: >
        {% if is_number(states('sensor.cgllc_cgd1st_c37c_co2_density')) %}
          {{ states('sensor.cgllc_cgd1st_c37c_co2_density') }}
        {% else %}
          {{ states('sensor.c_bedroom_co2_density') }}
        {% endif %}
      unit_of_measurement: "ppm"
      device_class: carbon_dioxide
      icon_template: mdi:molecule-co2
      # availability_template: "{{ is_number(states('sensor.cgllc_cgd1st_c37c_co2_density')) }}"

    # KIDSROOM CLIMATE
    c_kidsroom_temperature:
      friendly_name: "Kidsroom Temeperature"
      value_template: >
        {{ states('sensor.kidsroom_air_sensor_temperature') }}
      unit_of_measurement: "°C"
      device_class: temperature
      icon_template: mdi:thermometer
      availability_template: "{{ is_number(states('sensor.kidsroom_air_sensor_temperature')) }}"

    c_kidsroom_humidity:
      friendly_name: "Kidsroom Humidity"
      value_template: >
        {{ states('sensor.kidsroom_air_sensor_humidity') }}
      unit_of_measurement: "%"
      device_class: humidity
      icon_template: mdi:water-percent
      availability_template: "{{ is_number(states('sensor.kidsroom_air_sensor_humidity')) }}"

    c_kidsroom_pressure:
      friendly_name: "Kidsroom Pressure"
      value_template: >
        {{ states('sensor.kidsroom_air_sensor_pressure') }}
      unit_of_measurement: hPa
      device_class: atmospheric_pressure
      icon_template: mdi:thermometer-lines
      availability_template: "{{ is_number(states('sensor.kidsroom_air_sensor_pressure')) }}"

    # BATHROOM CLIMATE
    c_bathroom_temperature:
      friendly_name: "Bathroom Temeperature"
      value_template: >
        {{ states('sensor.bathroom_air_sensor_temperature') }}
      unit_of_measurement: "°C"
      device_class: temperature
      icon_template: mdi:thermometer
      availability_template: "{{ is_number(states('sensor.bathroom_air_sensor_temperature')) }}"

    c_bathroom_humidity:
      friendly_name: "Bathroom Humidity"
      value_template: >
        {{ states('sensor.bathroom_air_sensor_humidity') }}
      unit_of_measurement: "%"
      device_class: humidity
      icon_template: mdi:water-percent
      availability_template: "{{ is_number(states('sensor.bathroom_air_sensor_humidity')) }}"

    c_bathroom_pressure:
      friendly_name: "Bathroom Pressure"
      value_template: >
        {{ states('sensor.bathroom_air_sensor_pressure') }}
      unit_of_measurement: hPa
      device_class: atmospheric_pressure
      icon_template: mdi:thermometer-lines
      availability_template: "{{ is_number(states('sensor.bathroom_air_sensor_pressure')) }}"

    # KITCHEN CLIMATE
    c_kitchen_temperature:
      friendly_name: "Kitchen Temeperature"
      value_template: >
        {{ states('sensor.kitchen_air_sensor_temperature') }}
      unit_of_measurement: "°C"
      device_class: temperature
      icon_template: mdi:thermometer
      availability_template: "{{ is_number(states('sensor.kitchen_air_sensor_temperature')) }}"

    c_kitchen_humidity:
      friendly_name: "Kitchen Humidity"
      value_template: >
        {{ states('sensor.kitchen_air_sensor_humidity') }}
      unit_of_measurement: "%"
      device_class: humidity
      icon_template: mdi:water-percent
      availability_template: "{{ is_number(states('sensor.kitchen_air_sensor_humidity')) }}"

    c_kitchen_pressure:
      friendly_name: "Kitchen Pressure"
      value_template: >
        {{ states('sensor.kitchen_air_sensor_pressure') }}
      unit_of_measurement: hPa
      device_class: atmospheric_pressure
      icon_template: mdi:thermometer-lines
      availability_template: "{{ is_number(states('sensor.kitchen_air_sensor_pressure')) }}"

    # LIVING_ROOM CLIMATE
    c_livingroom_temperature:
      friendly_name: "Livingroom Temeperature"
      value_template: >
        {{ states('sensor.air_purifier_2s_temperature') }}
      unit_of_measurement: "°C"
      device_class: temperature
      icon_template: mdi:thermometer
      availability_template: "{{ is_number(states('sensor.air_purifier_2s_temperature')) }}"

    c_livingroom_humidity:
      friendly_name: "Livingroom Humidity"
      value_template: >
        {{ states('sensor.air_purifier_2s_humidity') }}
      unit_of_measurement: "%"
      device_class: humidity
      icon_template: mdi:water-percent
      availability_template: "{{ is_number(states('sensor.air_purifier_2s_humidity')) }}"

    c_livingroom_pm25_density:
      friendly_name: "Livingroom pm2.5 Density"
      value_template: >
        {{ states('sensor.air_purifier_2s_pm2_5') }}
      unit_of_measurement: "µg/m³"
      device_class: pm25
      icon_template: mdi:blur
      availability_template: "{{ is_number(states('sensor.air_purifier_2s_pm2_5')) }}"
