homeassistant: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: mqtt
  password: ttmq
serial:
  port: >-
    /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_c01ed14910b6ed11a16bd40ea8669f5d-if00-port0
  adapter: zstack
frontend:
  port: 8099
devices:
  '0x00158d000586695c':
    friendly_name: Bathroom Air Sensor
  '0x00158d0006bed661':
    friendly_name: Bathroom Motion Sensor
  '0x00158d00054cd813':
    friendly_name: Bedroom Closet Motion Sensor
  '0x00158d0006e4e280':
    friendly_name: Bathroom Door Sensor
  '0x04cf8cdf3c777c79':
    friendly_name: Bedroom Charging Dock Plug
  '0x04cf8cdf3c764d02':
    friendly_name: Kitchen Sink Plug
  '0x00158d00052fa079':
    friendly_name: Bedroom Aqara Cube
  '0x00158d0007bf1dd5':
    friendly_name: Bathroom Water Leak Sensor
  '0x04cf8cdf3c8eb0f3':
    friendly_name: Bathroom Light Switch
    state_action: true
  '0x00158d0008a9e22e':
    friendly_name: Hallway Door Sensor
  '0x54ef4410006ba559':
    friendly_name: Bedroom Left Cover
  '0x54ef4410006b96f2':
    friendly_name: Bedroom Right Cover
  '0x54ef441000410c67':
    friendly_name: Bedroom Light Switch
    state_action: true
  '0x54ef441000413c72':
    friendly_name: Kidsroom Light Switch
    state_action: true
  '0x00158d00076a7e3e':
    friendly_name: Hallway Push Sensor
  '0x00158d00052b3ad9':
    friendly_name: Bathroom Lamp
  '0x54ef4410006dc3dd':
    friendly_name: Bathroom Presence Sensor
  '0x54ef44100088155f':
    friendly_name: Livingroom Light Switch
    state_action: true
  '0xa4c138f4eb101032':
    friendly_name: Roborock Remote Control
  '0x54ef4410007df222':
    friendly_name: Kitchen Light Switch
    state_action: true
  '0xa4c1386f1ce92e1c':
    friendly_name: Bedroom Monitor Plug
  '0xa4c138e6cbe81d2a':
    friendly_name: Bedroom Remote Control
  '0xa4c1385d220cdc03':
    friendly_name: Kitchen Motion Sensor
  '0xa4c138756ba0746d':
    friendly_name: Livingroom PC Plug
  '0xa4c1387ee874ae6f':
    friendly_name: Bedroom Fan Plug
  '0xa4c1381eddafd03a':
    friendly_name: Kitchen Button
  '0xa4c1384d2b081bbd':
    friendly_name: Hallway Button
  '0xa4c1383084092912':
    friendly_name: Hallway Button Pusher
    state_action: true
  '0xa4c138443ed4b6bb':
    friendly_name: Kidsroom Button
  '0x54ef4410009d5c25':
    friendly_name: Hallway Light Switch
    state_action: true
  '0x54ef441000b9ea2a':
    friendly_name: Bedroom Heater Relay
  '0x00158d000af2836a':
    friendly_name: Bedroom Air Sensor
  '0xa4c138ee40adabe6':
    friendly_name: Kitchen Boiler Plug
  '0x00158d00075d7069':
    friendly_name: Bathroom Window Sensor
  '0x00158d0005800735':
    friendly_name: Kitchen Air Sensor
  '0x00158d0006ed6b85':
    friendly_name: Kidsroom Air Sensor
advanced:
  log_level: info
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  channel: 24
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
