##################   Автоматика
title: Вся автоматика
icon: mdi:script
cards:
  - type: vertical-stack
    cards:
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
          show_header_toggle: false
          title: Автоматизации Lights
        filter:
          include:
            - domain: automation
              name: "*Lights*"
              options:
                secondary_info: last-triggered
              sort:
                method: name
        exclude:
          - state: "off"

  - type: vertical-stack
    cards:
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
          show_header_toggle: false
          title: Автоматизации Other
        filter:
          include:
            - domain: automation
              not:
                name: "*Lights*"
              options:
                secondary_info: last-triggered
              sort:
                method: name

      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
          show_header_toggle: false
        filter:
          include:
            - domain: automation
              options:
                secondary_info: last-triggered
              sort:
                method: name
          exclude:
            - state: "on"

  - type: vertical-stack
    cards:
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
          show_header_toggle: false
          title: Скрипты
        filter:
          include:
            - domain: script
              options:
                secondary_info: last-triggered
              sort:
                method: attribute
                attribute: last_triggered
                reverse: true
          sort:
            method: entity_id
